blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://splunk-platform-apps.github.io/<add_repo_name>/docs
    about: Please check our documentation before opening an issue.
  - name: Community Forum
    url: https://splunkcommunity.slack.com/archives/C04DC8JJ6
    about: For general questions, use the forum instead of opening an issue.